In [8]:
import numpy as np
a=np.array([1,2,3,4,5,6,7,8,9])
slice1=a[2:6]
print(slice1)

[3 4 5 6]


In [13]:
slice2=a[::2]
print(slice2)

[1 3 5 7 9]


In [15]:
Reverse=a[::-1]
print(Reverse)

[9 8 7 6 5 4 3 2 1]


In [22]:
a=np.array([[1,2,3],[5,6,7],[8,9,0]])
b=a[0:2,1:3]
print(b)

[[2 3]
 [6 7]]


In [24]:
#extract first column
col=a[:,0]
print(col)


[1 5 8]


In [27]:
#extract row
row=a[2,:]
print(row)

[8 9 0]


In [29]:
print(a[0,0])
print(a[1,2])

1
7


In [34]:
#negative indexing
a=np.array([10,20,30,40,50])
print(a[-1])

50


In [35]:
print(a[1:4])

[20 30 40]


In [36]:
#index an element that needs an specific condition
print(a[a>20])

[30 40 50]


In [38]:
a1=np.array([[1,2],[3,4]])
a2=np.array([[5,6],[7,8]])
result=np.hstack((a1,a2))
print(result)

[[1 2 5 6]
 [3 4 7 8]]


In [39]:
result=np.dstack((a1,a2))
print(result)

[[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]


In [51]:
arr=np.array([1,2,3,4,5,6])
result=np.split(arr,3)
print(result)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [52]:
result=np.array_split(arr,3)
print(result)

[array([1, 2]), array([3, 4]), array([5, 6])]
